# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JavaScript-XRay
version:      0.97
version_from: lib/JavaScript/XRay.pm
installdirs:  site
requires:
    Carp:                          0
    LWP::Simple:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
